POST http://127.0.0.1:8080/events
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wbGVAbWFpbC5jb20iLCJleHAiOjE3MjI3Nzk5MTksInVzZXJfaWQiOjF9.MoD7MUYP8CaP7Y9RbTzWygDU3CpV8qP719V4xQzGDjQ

{
    "name": "Test Event",
    "description": "A test location",
    "dateTime": "2024-01-01T15:30:00.000Z",
    "location": "Lviv"
}