POST http://127.0.0.1:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wbGUzQG1haWwuY29tIiwiZXhwIjoxNzIyNzc1Nzc2LCJ1c2VyX2lkIjowfQ.E_SYsdQWJM__4YsatBIqIi6GBHtBcf0Hpg6dyDXjn10

{
    "name": "Test Event",
    "description": "A test location",
    "dateTime": "2024-01-01T15:30:00.000Z",
    "location": "Lviv"
}