PUT http://localhost:8080/events/1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wbGVAbWFpbC5jb20iLCJleHAiOjE3MjI3ODAwMDIsInVzZXJfaWQiOjF9.qoAWi3L_-fplNvJV5h6visSeOoCaj_aY8_yJOB2Xl6w

{
    "name": "Updated test event",
    "description": "updated",
    "location": "Test location updated",
    "dateTime": "2024-01-01T15:30:00Z"
}